development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: vdlib_dev
  pool: 5
  username: dlib
  password: "123456"
  socket: /var/run/mysqld/mysqld.sock # need check existence

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: vdlib_dev
  pool: 5
  username: dlib
  password: "123456"
  socket: /var/run/mysqld/mysqld.sock # need check existence

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: vdlib
  pool: 5
  username: dlib
  password: "123456"
  socket: /var/run/mysqld/mysqld.sock # need check existence
